name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    # env:
    #   args: blue
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - name: Set env var
        run: |
          echo "args=-DsomeModule.skip.tests=true" >> "$GITHUB_ENV"
        shell: bash
        if: runner.os == 'Windows'

      - name: Test command with env var
        run: echo "mvn ${{ env.args }} test"
