name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
    steps:
      - name: Test wsl
        run: |
              wsl --set-default-version 2
              wsl --install -d Ubuntu
              wsl -l -v
        if: runner.os == 'Windows' && ${{ always() }}
      - name: Test docker on windows-latest
        run: docker run --rm hello-world
        if: runner.os == 'Windows' && ${{ always() }}
      - name: Test linux docker container on windows-latest
        run: docker run --rm ubuntu:latest echo test
        if: runner.os == 'Windows' && ${{ always() }}
      - name: Test docker via wsl on windows-latest
        run: wsl docker run --rm hello-world
        if: runner.os == 'Windows' && ${{ always() }}
